<script setup lang="ts">
export interface ToastAction { label: string; action: () => void }
const visible = defineModel<boolean>({ required: true })
withDefaults(defineProps<{ title?: string; body?: string; icon?: string; imageSrc?: string; actions?: ToastAction[]; hideClose?: boolean }>(), {})
defineEmits<{ close: [] }>()
</script>

<template>
  <Teleport to="body"><Transition name="a-toast"><aside v-if="visible" class="a-toast" role="status"><button v-if="!hideClose" type="button" class="a-toast__close" aria-label="Cerrar notificación" @click="visible = false; $emit('close')"><q-icon name="close" /></button><div v-if="icon" class="a-toast__icon"><q-icon :name="icon" /></div><div class="a-toast__text"><strong v-if="title">{{ title }}</strong><p v-if="body">{{ body }}</p></div><img v-if="imageSrc" :src="imageSrc" alt="" /><div v-if="actions?.length" class="a-toast__actions"><button v-for="action in actions" :key="action.label" type="button" @click="action.action">{{ action.label }}</button></div></aside></Transition></Teleport>
</template>

<style scoped>
.a-toast { position: fixed; z-index: var(--a-z-toast); right: var(--a-space-5); bottom: var(--a-space-5); display: grid; grid-template-columns: auto minmax(0, 1fr); gap: var(--a-space-3); width: min(var(--a-layout-toast), calc(100vw - var(--a-space-8))); padding: var(--a-space-4); border: var(--a-border-width) solid var(--a-border-strong); border-radius: var(--a-radius-md); background: var(--a-text-primary); color: var(--a-bg-raised); box-shadow: var(--a-shadow-2); }.a-toast__close { position: absolute; top: var(--a-space-1); right: var(--a-space-1); display: grid; width: var(--a-target-min); height: var(--a-target-min); place-items: center; border: 0; border-radius: var(--a-radius-sm); background: transparent; color: inherit; opacity: .72; cursor: pointer; }.a-toast__close:hover { background: var(--a-bg-inverse-muted); opacity: 1; }.a-toast__icon { display: grid; place-items: center; width: var(--a-target-min); height: var(--a-target-min); border-radius: var(--a-radius-sm); background: var(--a-bg-inverse-muted); font-size: var(--a-icon-md); }.a-toast__text { min-width: 0; padding-right: var(--a-target-min); }.a-toast__text strong { font-size: var(--a-font-size-sm); }.a-toast__text p { margin: var(--a-space-1) var(--a-space-0) var(--a-space-0); opacity: .82; font-size: var(--a-font-size-xs); line-height: var(--a-line-height-body); }.a-toast__actions { grid-column: 2 / -1; display: flex; flex-wrap: wrap; gap: var(--a-space-2); }.a-toast__actions button { min-height: var(--a-target-min); border: 0; border-radius: var(--a-radius-sm); padding: var(--a-space-2) var(--a-space-3); background: var(--a-bg-inverse-muted); color: inherit; font-weight: var(--a-font-weight-semibold); cursor: pointer; }.a-toast__actions button:hover { background: var(--a-bg-inverse-hover); }.a-toast-enter-active,.a-toast-leave-active { transition: opacity var(--a-motion-base), transform var(--a-motion-base); }.a-toast-enter-from,.a-toast-leave-to { opacity: 0; transform: translateY(var(--a-space-3)) scale(.98); }
@media (max-width: 32rem) { .a-toast { right: var(--a-space-4); bottom: var(--a-space-4); } }
</style>
